# 1. Perform a set of exercises

### Excercise 1.  
Enter the number n. Output an array of size nхn, in which thediagonals are numbers from 1 to n, and other elements are 0

In [6]:
import numpy as np

def generate():
    a = int(input("Enter: "))
    for x in range(1,a + 1):
        yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
x = np.diag(Z)

print(x)


Enter: 5
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


#### Excercise 3. 
Enter 4 numbers n, m, r, c. Output an array of size nхm, in which ineach r -th row and in each c-th column are 0, and other elements are equal to 1.

In [8]:
import numpy as np

n =int(input(" enter the number :"))
m =int(input(" enter the number :"))
r =int(input(" enter the number :"))
c=int(input(" enter the number :"))
arr = np.ones((n, m), dtype=int)

arr[::r, :] = 0
arr[:,::c] = 0
print(arr)

 enter the number :6
 enter the number :7
 enter the number :2
 enter the number :3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


### Excercise 4. 
Enter the numbers n and m. Output an array of size nхm, in which the first line (line with zero index) are numbers from 0 to m-1, and all other elements
of the matrix are equal to 0.

In [9]:
import numpy as np

n =int(input(" enter the number :"))
m =int(input(" enter the number :"))
arr = np.zeros((m, n), dtype=int)

arr[0,:] = np.arange(0, n)
print(arr)

 enter the number :3
 enter the number :4
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


### Excercise 6.
An array is entered from the keyboard. Replace all non-zero elements with -1.

In [10]:
def matr(arr):
    arr[arr != 0] = -1
    return arr
a = np.array([int(i) for i in input(": ").split()])
print(matr(a))

: 3 4 0 9 7 0 6 0 4 0 3
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


### Excercise 10. 
Enter the numbers n and m. Create an array of random values of size nхn and calculate the minimum, maximum value, mean and standard deviation, rounded to 3 decimal places

In [11]:
def rnd(n,m):
    arr = np.random.random((n,m))
    print(arr.max())
    print(arr.min())
    print(arr.mean())
    print(arr.std())
rnd(5,5)

0.9782440401766773
0.004241624059050153
0.47799416490254765
0.31388769162401714


### Excercise 12. 
Create an array of 1 of size nхn and create an inside "border" formed from 0.

In [12]:
import numpy as np
n =int(input(" enter"))
arr = np.ones((n, n), dtype=int)
arr[0] = 0
arr[-1] = 0
arr[:, 0] = 0
arr[:, -1] = 0
print(arr)
arr[0]=0

 enter4
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


### Excercise 15. 
Arrange 1 and 0 on the 8х8 field in a checkerboard pattern using the numpy tile().

In [13]:
def rng():
    return np.tile([0,1], (8,8))
print(rng())

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


### Excercise 17. 
Fill the vector with values from 0 to n. Replace all values greater than n/2 and less than 3n/4 with zeros.

In [14]:
import numpy as np

n = int(input("Enter a number : "))
x = np.arange(n+1)
l, r = np.split(x, [n//4+1])
r[r < 3*n/4] = 0
print(x)

Enter a number : 10
[ 0  1  2  0  0  0  0  0  8  9 10]


### Excercise 18. 
Fill the vector with values from 0 to n. Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones.

In [15]:
def fun18(n):
    arr = np.arange(0,n+1)
    arr[(arr < n/2) ^ (arr > 3*n/4)] *= -1
    return arr
print(fun18(10))

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


### Excercise 22. 
Enter the numbers n and m. Generate a matrix nхn of random intege r elements from 0 to m. Change the signs of all maximum elements to the opposite

In [16]:
import numpy as np

n =int(input(" enter the number :"))
m =int(input(" enter the number :"))
Z = np.random.randint(m, size=(n, n))

Z0 = np.where(Z == Z.max(), (-1)*Z.max(), Z)

print(Z0)

 enter the number :4
 enter the number :10
[[ 6  6  4  1]
 [ 1 -9  0  5]
 [ 2  8  5  3]
 [ 5  0  7  4]]


## 2. Solve the system of linear equations using Cramer's formulas and perform a test using:¶
### a) matrix multiplication;
### b) numpy.linalg.solve().

In [17]:
def cramer(mA, B):
    n = mA.shape[0]
    det = np.linalg.det(mA)
    xs = np.empty(n)
    if det == 0:
        return None
    for i in range(n):
        mAi = np.copy(mA)
        mAi[:, i] = B
        xs[i] = np.linalg.det(mAi) / det
    return xs
A = np.array([[1, 5, 3, -4], [3, 1, -2, 0], [5, -7, 0, 10], [0, 2, -5, 0]])
B = np.array([20, 9, -9, 1])
roots = cramer(A, B)
print(roots)
print(np.linalg.solve(A,B))
ax = np.dot(A,roots)
print(ax)
print(np.allclose(ax, B))

[ 2.69166667  2.625       0.85       -0.40833333]
[ 2.69166667  2.625       0.85       -0.40833333]
[20.  9. -9.  1.]
True


### 3. Calculate the value of the matrix expression

In [18]:

A = np.array([[5,2,0],[10,4,1],[7,3,2]], dtype=int)
B = np.array([[3,6,-1],[-1,-2,0],[2,1,3]], dtype=int)

print((A-(B*B))*(2*A+B))

[[ -52 -340    1]
 [ 171    0    2]
 [  48   14  -49]]


## 4. Solve the matrix equation using an inverse matrix and perform a test using:¶
### a) matrix multiplication;
### b) numpy.linalg.solve().

In [20]:
a = np.array([[2,3,1],[4,-1,0],[0,1,2]])
b = np.array([[9,8,7],[2,7,3],[4,3,5]])
def solve(mA, mB):
    if np.linalg.det(mA) == 0:
        return None
    X = np.linalg.inv(mA) @ mB
    return X


roots = solve(a,b)
print(roots)
print(np.linalg.solve(a,b))
toor = a @ roots
print(toor)
print(np.allclose(prod,b))

[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]]
[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]]
[[9. 8. 7.]
 [2. 7. 3.]
 [4. 3. 5.]]
True
